[build]
builder = "nixpacks"

[deploy]
startCommand = "python reset_db.py && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
